compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthIdent: 'phantomjinx:c6r1st1n3'

npmPublishRegistry: 'http://192.168.88.5:4873'

npmRegistryServer: 'http://192.168.88.5:4873'

unsafeHttpWhitelist:
  - localhost
  - 192.168.88.5

yarnPath: .yarn/releases/yarn-4.5.0.cjs
